### PR TITLE
Merge cherrypicking samples view changes

### PR DESCRIPTION
**Pull request by emrojo**
Closes GPL769

Changes proposed in this pull request:

* Integrate view access with GPL842

### CODE REVIEW

**Comment by emrojo** [comment]
Convert to draft, as it happens we might need to recover the workflow for uwh and ewh, in order to use the new view.

**Comment by emrojo** [comment]
Is related with https://github.com/sanger/unified_warehouse/pull/200

**Review by KatyTaylor — DISMISSED** [review]

**Comment by harrietc52** [comment]
Tests:
- [ ] Running the 'positives on site report' before deploying this to see if it alters the performance.
- [ ] Deploy
- [ ] Running the 'positives on site report' after deploying this to see if it alters the performance.

**Review by harrietc52 — APPROVED** [review]

**Comment by emrojo** [comment]
Time before deploying without the new view:
image

Time after deploying using the view:
image

**Review by stevieing — APPROVED** [review]

**Pull request merged**
